### ISSUE TITLE
Code coverage based on concrete tests only

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/flow#309]
Currently, code coverage includes both fuzz and concrete tests. The fuzz tests require that functions are not reverting. That's why we use `assume` and `bound` in them. Thus, they only test for non reverting situations.

On the other hand, concrete tests is to test for each and every line and all possible branches, which is what coverage should be telling us. Currently, even if some of the branches are missed in concrete but called in fuzz, the coverage will not be able to detect that.

An example is missing `notNull` modifier in `isTransferrable` ([cantina finding](https://cantina.xyz/code/99ae802b-f05c-4e36-a1d1-240d5146649c/findings/2)).

Thus, I propose to run coverage only using concrete tests.

RFC @sablier-labs/solidity.

Here is a comparison. As you can see the coverage for `SablierFlow.sol` went down when calculating it based on concrete tests, demonstrating that there are missing concrete tests for some lines / branches.

| `--mp "tests/{integration}/**/*.sol"` | `--mp "tests/integration/concrete/**/*.sol"` |
| -- | -- |
| <img width="890" alt="Screenshot 2024-10-15 at 12 02 17" src="https://github.com/user-attachments/assets/6df0b168-711e-485e-b684-06be85156b34"> | <img width="890" alt="Screenshot 2024-10-15 at 12 03 28" src="https://github.com/user-attachments/assets/55fc660f-3db2-441d-b386-90b2957ddc86"> |

PS: similar suggestion for lockup.

**Comment by andreivladbrg** [comment]
> increased coverage for SablierFlowBase, with concrete tests, to 100% on all

great news

> it only increased coverage for `SablierFlow` by 0.2%-0.4% (just a note and no call to action at this time).

oh, that's less that i would've estimate, interesting, thanks for the update

**Comment by smol-ninja** [comment]
Post https://github.com/sablier-labs/v2-core/issues/1105, I have realized that its a good idea to run codecov based on all the tests and not only concrete tests. So I will close this issue as not planned. Feel free to re-open it if you feel otherwise.

Now regarding the problem of identifying missing concrete tests, we can run `forge coverage` locally on concrete tests once in a while to see if there are missing tests that should have been implemented and create issue for them separately.
