### ISSUE TITLE
Implement `IBatch` interface

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/flow#325]
## To do

- [x] Implement `IBatch` interface
- [x] Inherit `IBatch` into `ISablierFlowBase`

**Comment by smol-ninja** [comment]
@andreivladbrg would you like to take it since you have worked on the same feature in Lockup?

**Comment by TheMarvelFan** [comment]
@smol-ninja 

I would like to work on this if you accept external contributions.

**Comment by smol-ninja** [comment]
Hi @TheMarvelFan. Yes you can work on it. You can refer to https://github.com/sablier-labs/v2-core/pull/1070 for reference.

**Comment by TheMarvelFan** [comment]
@smol-ninja 

I have created a PR for this issue. Please review the changes and let me know if further modifications are required.

Thanks!

**Comment by smol-ninja** [comment]
Thanks for the PR @TheMarvelFan
