### ISSUE TITLE
ETH fees in withdraw function

### ISSUE THREAD

**Issue by PaulRBerg** [sablier-labs/flow#328]
The design should be the same as in [Lockup](https://github.com/sablier-labs/v2-core/issues/1076).

### Discussed in https://github.com/sablier-labs/flow/discussions/327

<div type='discussions-op-text'>

<sup>Originally posted by **PaulRBerg** November  6, 2024</sup>
We've recently decided to charge [ETH fees](https://github.com/sablier-labs/v2-core/issues/1076) instead of [protocol fees](https://github.com/sablier-labs/v2-core/issues/1034) in Lockup. ETH fees make much more sense for Lockup streams per all the reasons provided [here](https://github.com/sablier-labs/company-discussions/discussions/72#discussioncomment-11115807).

Now, for Flow streams, the fee is paid in stablecoin. This is not bad, but I wonder if charging in ETH wouldn't be better?

1. More consistency across our fee models
2. Less psychological resistance; the user has to pay a fee in ETH anyway (for the gas), so charging $1 in ETH should feel less pressuring than paying a *separate* fee in USDC (from the recipient's salary)
3. Charging in ETH means that we are charging the account that withdraws, not the recipient (these accounts might not be the same)

Notes:

- I'm not suggesting to change the implementation now because doing so would cancel the validity of the security audits.
- We will start charging in ~March anyway, so changing the implementation in Flow now would be overkill.

Cc @sablier-labs/everybody for feedback.</div>

### Tasks
- [x] https://github.com/sablier-labs/flow/issues/338

**Comment by smol-ninja** [comment]
Great idea. Does this also mean removing existing implementation of protocol fee?

**Comment by PaulRBerg** [comment]
Thank you.

TBD if we remove the protocol fees. We should carefully listen to user feedback.

**Comment by andreivladbrg** [comment]
> TBD if we remove the protocol fees. We should carefully listen to user feedback

given the short period between `v1.0.0` and `v1.0.1`, there will be no time to "listen to user feedback" - soo, should we keep it, or remove it?

**Comment by PaulRBerg** [comment]
The next version will be `1.1.0`

Let's keep the protocol fees because doing so would result in a smaller diff, and this is important for getting this audited sooner.

**Comment by andreivladbrg** [comment]
> result in a smaller diff, and this is important for getting this audited sooner

good point
