### ISSUE TITLE
Revert BatchError with index

### ISSUE THREAD

**Issue by smol-ninja** [sablier-labs/flow#353]
From [Akshat's tweet](https://x.com/iakshatmittal/status/1870114989924606450?s=46&t=VYM6cpSayUkPRiVfjoKB-Q):

It would be a good idea to include index in BatchError in order to trace down the failing call.

Regarding return value, I am not sure how could that be useful. Let me know your thoughts on this.

cc @sablier-labs/solidity

**Comment by andreivladbrg** [comment]
good idea, i like it

**Comment by PaulRBerg** [comment]
Thanks Shub, closing in favor of #354.
